[build]
  command = "npm run build:netlify"
  publish = "_site"

[context.production]
  environment = { ELEVENTY_ENV = "production" }

[context.deploy-preview]
  environment = { ELEVENTY_ENV = "development" }

[context.branch-deploy]
  environment = { ELEVENTY_ENV = "development" }

[context.storybook]
  command = "npm run build:storybook"
  publish = "_styleguide"

[[headers]]
  for = "/assets/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; script-src 'self' https://plausible.io 'unsafe-inline'; connect-src 'self' https://plausible.io; img-src 'self' data: https://res.cloudinary.com; style-src 'self' 'unsafe-inline'; font-src 'self' data:; media-src 'self' https://www.dropbox.com https://dl.dropboxusercontent.com; manifest-src 'self'"
    Cache-Control = "public, max-age=0, must-revalidate"
